apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-movietask-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Movie-task Management"
    rbac.authorization.halo.run/ui-permissions: '["plugin:movietask:view"]'
    rbac.authorization.halo.run/display-name: "影库查看"
rules:
  - apiGroups: [ "movietask.halo.run"]
    resources: [ "movietask" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/movietask" ]
    resourceNames: [ "PluginMovieTask" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-movietask-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: '["role-template-movietask-view"]'
    rbac.authorization.halo.run/ui-permissions: '["plugin:movietask:manage"]'
    rbac.authorization.halo.run/module: "Movie-task Management"
    rbac.authorization.halo.run/display-name: "影库管理"
rules:
  - apiGroups: [ "movietask.halo.run"]
    resources: [ "movietask" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/movietask" ]
    resourceNames: [ "PluginMovieTask" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
